<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Remember my ID_a-rd86wfjvcj46</name>
   <tag></tag>
   <elementGuidId>5a74a2e6-0fb2-4b3b-b618-3fd3bb1b136a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-rd86wfjvcj46']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-rd86wfjvcj46&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;a-rd86wfjvcj46&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>664db5e0-dcce-42cb-adf2-52b06b26e746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>aac238ac-f727-4757-8fe2-d625a1872524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>4697d44d-3923-4f24-9666-c7c2f51c1524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>5b8374ae-4a56-44d2-8302-a71a88a5ce04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>5aa4ef6e-85f1-46f6-8cfa-497b74847a69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-rd86wfjvcj46</value>
      <webElementGuid>48d983eb-23ef-4294-9a3c-95265baf0358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b09a7aff-85f3-4f53-b836-7a8f164749ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>718c7084-6092-4bb4-917c-5dd4dc2eb9e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>b94228c3-cef9-4e4d-a00e-5347e69205ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LeLBNcoAAAAAKgubPPOcLquiNjsR9F6Hljch42c&amp;co=aHR0cHM6Ly9hY2NvdW50LnNhbXN1bmcuY29tOjQ0Mw..&amp;hl=en&amp;v=I0bG74fWAenNf3Z5ncHSz-bd&amp;size=normal&amp;cb=9erkgwcveo27</value>
      <webElementGuid>d9515452-1bdb-49cd-93dc-5fbdcaeb3ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;one-card-ui ng-scope block-ui block-ui-anim-fade&quot;]/div[@class=&quot;wrapper ng-scope&quot;]/main[@class=&quot;one-main new-login ng-scope&quot;]/div[@class=&quot;main-inner&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;one-forms-login&quot;]/form[@class=&quot;ng-valid ng-valid-maxlength ng-dirty ng-valid-parse&quot;]/fieldset[1]/div[@class=&quot;mbr_signin&quot;]/div[@class=&quot;one-btn-container&quot;]/div[@class=&quot;one-captcha-container&quot;]/div[@class=&quot;one-chptcha ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;captchaContainer&quot;]/div[@class=&quot;g-recaptcha ng-pristine ng-untouched ng-valid ng-empty&quot;]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>418fd236-6fcb-4d2e-a7f3-6cd1dcd38a07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-rd86wfjvcj46']</value>
      <webElementGuid>e2b5a14f-fe2e-4e47-86f5-e3bd89683cd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>77ee6b59-dbe9-40c3-81e1-b417dcae3490</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-rd86wfjvcj46' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LeLBNcoAAAAAKgubPPOcLquiNjsR9F6Hljch42c&amp;co=aHR0cHM6Ly9hY2NvdW50LnNhbXN1bmcuY29tOjQ0Mw..&amp;hl=en&amp;v=I0bG74fWAenNf3Z5ncHSz-bd&amp;size=normal&amp;cb=9erkgwcveo27']</value>
      <webElementGuid>bd9cba5b-2376-405d-960f-b8a68926deec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
