<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Too many failed attempts_VfPpkd-muHVF_8ead10</name>
   <tag></tag>
   <elementGuidId>e0fdd3b4-fa50-4e66-ac31-c7c01cc05e26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.VfPpkd-muHVFf-bMcfAe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Show password&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f6ae365f-ab70-48c4-9e66-177701d94627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>VfPpkd-muHVFf-bMcfAe</value>
      <webElementGuid>74c2982c-e750-4473-a5e1-e6c0e48c1e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>79f17398-22f0-4e3e-99d9-947da7155f3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>YPqjbf</value>
      <webElementGuid>44898980-970c-4283-856b-2d0dd5d29f7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsaction</name>
      <type>Main</type>
      <value>focus:AHmuwe; blur:O22p3e;change:WPi0i;</value>
      <webElementGuid>90b45634-310e-40b5-8048-3069faa029b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>selectionc1</value>
      <webElementGuid>20763e95-2bc6-4c72-a833-4b7405f01721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yDmH0d&quot;)/c-wiz[@class=&quot;A77ntc&quot;]/div[@class=&quot;Svhjgc&quot;]/div[@class=&quot;UXFQgc&quot;]/div[@class=&quot;qWK5J&quot;]/div[@class=&quot;xKcayf&quot;]/div[@class=&quot;AcKKx&quot;]/form[1]/span[1]/section[@class=&quot;Em2Ord&quot;]/div[@class=&quot;yTaH4c&quot;]/div[1]/div[@class=&quot;njnYzb NhPs4c&quot;]/div[@class=&quot;v8aRxf&quot;]/div[@class=&quot;myYH1 g9Mx QkTfte&quot;]/div[@class=&quot;Hy62Fc&quot;]/div[@class=&quot;sfqPrd rBUW7e&quot;]/div[@class=&quot;QTJzre NEk0Ve&quot;]/div[@class=&quot;uxXgMe&quot;]/div[@class=&quot;VfPpkd-dgl2Hf-ppHlrf-sM5MNb&quot;]/div[@class=&quot;VfPpkd-MPu53c VfPpkd-MPu53c-OWXEXe-dgl2Hf Ne8lhe swXlm az2ine lezCeb kAVONc VfPpkd-MPu53c-OWXEXe-mWPk3d VfPpkd-ksKsZd-mWPk3d-OWXEXe-Tv8l5d-lJfZMc VfPpkd-ksKsZd-mWPk3d-OWXEXe-AHe6Kc-XpnDCe VfPpkd-ksKsZd-mWPk3d VfPpkd-ksKsZd-mWPk3d-OWXEXe-ZNMTqd&quot;]/input[@class=&quot;VfPpkd-muHVFf-bMcfAe&quot;]</value>
      <webElementGuid>995f11bd-5e4a-4078-9692-96af9593da1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>2bba76ee-d234-49e2-a638-bdc19d19e234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='checkbox']</value>
      <webElementGuid>20523a48-6bda-4891-a895-b1dd22ec70c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yDmH0d']/c-wiz/div/div[2]/div/div/div/form/span/section[2]/div/div/div/div[3]/div/div/div/div/div/div/div/input</value>
      <webElementGuid>ae48d2e5-6c00-425b-bf6c-2ee74ed88c5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/input</value>
      <webElementGuid>d4ea705a-0b0a-4894-90ad-1c97704c8ad9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
