<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form</name>
   <tag></tag>
   <elementGuidId>3c367245-5b7e-4e5a-b571-eef3d898d817</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ext-gen2UploadBtn > form</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;ext-gen2UploadBtn&quot;)/form[1][count(. | //*[@ref_element = 'Object Repository/Page_OWS/iframe_W2W Order List by Admin_1707038958411']) = count(//*[@ref_element = 'Object Repository/Page_OWS/iframe_W2W Order List by Admin_1707038958411'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='file']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>f1965a4c-1e75-453b-8564-fd01b86e8b15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>method</name>
      <type>Main</type>
      <value>POST</value>
      <webElementGuid>a772a3bb-e243-4dce-a372-cb17cf68c3d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enctype</name>
      <type>Main</type>
      <value>multipart/form-data</value>
      <webElementGuid>37cc242d-902d-40e1-8e2a-abd479c9a1ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>action</name>
      <type>Main</type>
      <value>/adc-file/web/rest/v1/file/upload</value>
      <webElementGuid>ad27a70d-1069-4e5b-a8b4-4d871ad4df63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext-gen2UploadBtn&quot;)/form[1]</value>
      <webElementGuid>f503292e-1ed0-46c5-9772-b7ac009a76d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_OWS/iframe_W2W Order List by Admin_1707038958411</value>
      <webElementGuid>045c8a3a-25e3-4903-bece-bf1ac40e22bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form[@action='/adc-file/web/rest/v1/file/upload']</value>
      <webElementGuid>87810bc0-67d5-49e7-b137-3bd211e0bb5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='ext-gen2UploadBtn']/form</value>
      <webElementGuid>dddad478-5dfe-4182-bf3a-d185dde3f71e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[1]/following::form[1]</value>
      <webElementGuid>8188b913-8749-46da-af03-b2bed2341a8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload file'])[1]/following::form[1]</value>
      <webElementGuid>c2956382-451b-4768-9755-96d6fae7f75b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remark'])[1]/preceding::form[1]</value>
      <webElementGuid>7935a8c0-a343-48bd-b3aa-3d7344759755</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/form</value>
      <webElementGuid>67c2bcc0-6f5d-41de-a06f-dab07f9e6c3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
