<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_W2W Order List by Admin_1707038958411</name>
   <tag></tag>
   <elementGuidId>d596e86a-de53-4b3b-95f3-38f95ad03ce8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ky-1742465550']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ky-1742465550</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>0b84d7a6-f3cb-4814-8532-21f4c614e9b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ky-1742465550</value>
      <webElementGuid>6caf2d22-101f-44b9-a751-fbd1b72dade1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ows-frame-panel</value>
      <webElementGuid>94a882d7-9517-4da6-bf0d-1315253f2428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>4f0c3f75-4976-451c-81d5-b71a96714ab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>5d7a36a1-0dfa-4f63-b68b-d9e31eef012a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>1707038958411</value>
      <webElementGuid>12b213f8-d0b5-43ad-9f33-321eebf870d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/app/107d/spl/digital_distribution/digdis_w2w_order_list_prod.spl</value>
      <webElementGuid>a2de4d70-8bf9-4b3d-948c-ef24731a7e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>54b96fd4-2850-47c2-86b1-20966c99a3cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ky-1742465550&quot;)</value>
      <webElementGuid>d00dab40-b00a-4084-956b-d58f6f187d62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ky-1742465550']</value>
      <webElementGuid>965b5433-720f-4f08-9663-d205a7a1aa39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pane-ky-1742465550']/div/iframe</value>
      <webElementGuid>0f48f1a7-8067-48c4-8dbc-09d0ee252d0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/iframe</value>
      <webElementGuid>ecee9c2d-6912-4c66-a964-5eade543d675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ky-1742465550' and @name = '1707038958411' and @src = '/app/107d/spl/digital_distribution/digdis_w2w_order_list_prod.spl']</value>
      <webElementGuid>20577aab-0b86-4ed8-b20b-8bf270ddc33a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
