<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ship Your Idea quantity_cart72b32a1f7_27d9ff</name>
   <tag></tag>
   <elementGuidId>bbde8485-3eb2-453f-8ae8-5d7bc9f9f143</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#quantity_6423f7a99a013</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-8']/div/div/form/table/tbody/tr/td[5]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>39c6e9c5-99cc-4971-af4f-b5ae09ebe524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>339600cf-7f10-4e22-b5a9-79f90b94e6fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>quantity_6423f7a99a013</value>
      <webElementGuid>caa55d12-4e10-49b2-8fcb-c25eb7bd1fa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text qty text tdfocus-1680078764190</value>
      <webElementGuid>e53753f3-122e-4a05-a918-44a575bad43c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8afe01f0-92d0-41a2-9cce-f7b693ead0fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fb6d6542-6e57-45ba-b064-e239b2000923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cart[72b32a1f754ba1c09b3695e0cb6cde7f][qty]</value>
      <webElementGuid>59a05740-6d7f-49b3-915a-6b4b01ff7a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>b41800d3-a4cd-4796-9bbf-9f90ba5400a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Qty</value>
      <webElementGuid>8bd295a2-78d9-4d83-85b1-c5a7f41fc624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>11d5b4c6-0ec9-434e-a660-164e91e94851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>c632ecd0-1989-48ee-baaf-4b5b78540166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quantity_6423f7a99a013&quot;)</value>
      <webElementGuid>b2899c26-2178-445b-a458-f29c56a8ce19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='quantity_6423f7a99a013']</value>
      <webElementGuid>fb3275c0-de3f-4297-adf3-6e2d97487a05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-8']/div/div/form/table/tbody/tr/td[5]/div/input</value>
      <webElementGuid>c652e91a-5069-4acb-bb99-a986c298bca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b199862f-766c-4ebc-a95d-ac96744bee95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'quantity_6423f7a99a013' and @name = 'cart[72b32a1f754ba1c09b3695e0cb6cde7f][qty]' and @title = 'Qty']</value>
      <webElementGuid>3314e4ec-a8a7-45e0-9851-b828cb6a39ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
