<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Venezuela</name>
   <tag></tag>
   <elementGuidId>520a9e24-0d41-4b80-b670-60cf037abe15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-calc_shipping_country-result-pjb4-VE</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='select2-calc_shipping_country-results']/li[241]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>4c1ece8c-aec2-4435-b73a-a401d599d5f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>6095442e-91e6-4277-8bd6-3058cbd97671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-calc_shipping_country-result-pjb4-VE</value>
      <webElementGuid>dc81f62b-e35e-431b-9f48-e364eec138dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>bfe59686-5d01-40e0-9374-175677d49fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bb3141ef-9217-40b6-a7c0-12227dc3cd4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>19aece3f-146d-4ad8-801c-e5f62a0e9ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d1877a6a-de69-46b8-b283-f2a3a573b980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Venezuela</value>
      <webElementGuid>bef3de19-b598-44be-b96a-9cb2298ce26b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-calc_shipping_country-result-pjb4-VE&quot;)</value>
      <webElementGuid>a5c3fd23-009a-45e3-97d4-ac1b194d49e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-calc_shipping_country-result-pjb4-VE']</value>
      <webElementGuid>21880bf4-b155-4f62-9cd6-918cf5569670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-calc_shipping_country-results']/li[241]</value>
      <webElementGuid>73c9b66c-6814-4104-8e31-8001bc951ab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vatican'])[2]/following::li[1]</value>
      <webElementGuid>98d440e1-1b41-43bf-8b88-5331efd21518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vanuatu'])[2]/following::li[2]</value>
      <webElementGuid>b4991197-96fe-4b41-b2b1-84801168498d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vietnam'])[2]/preceding::li[1]</value>
      <webElementGuid>ee30a508-20ff-4ee9-bb34-4d6e91499da8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Virgin Islands (British)'])[2]/preceding::li[2]</value>
      <webElementGuid>ba605d4f-3961-4934-ad94-e5cdef537eb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[241]</value>
      <webElementGuid>4f34ceb8-06a8-4790-8bf8-74f8a6d7ee3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-calc_shipping_country-result-pjb4-VE' and (text() = 'Venezuela' or . = 'Venezuela')]</value>
      <webElementGuid>180bf2ae-6569-40b8-8958-023faf6c4a9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
