<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zisti viac_id-m22ra6yanu303sehyor-input</name>
   <tag></tag>
   <elementGuidId>c4578878-9729-40be-90e2-bdbb89bd8a36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id-m22ra6yanu303sehyor-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login']/div/div/div[2]/div/div/div/div/div/div/div/div/div[2]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Zadajte e-mail alebo mobil Mail a mobil nahrádza doterajšie prihlasovacie meno a heslo.Zistiť viacMail a mobil nahrádza doterajšie prihlasovacie meno a heslo.Zistiť viac&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e19a0de6-7a52-442c-a2dd-22a48e097186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-m22ra6yanu303sehyor-input</value>
      <webElementGuid>52009470-3d5f-4c45-8856-d590a7e69add</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e5ceea3a-4fc9-4ef0-b6f0-f9bfaa6b7111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>form</name>
      <type>Main</type>
      <value>id-m22ra6y6hg3w389tye-form</value>
      <webElementGuid>e095c85b-8510-46da-aa87-fbb3bce8eea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-m22ra6yanu303sehyor-input&quot;)</value>
      <webElementGuid>b39c5608-159e-4fa1-9585-10c01ae893c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id-m22ra6yanu303sehyor-input']</value>
      <webElementGuid>c0a954f4-7fce-479e-811c-bc8023b6d88d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login']/div/div/div[2]/div/div/div/div/div/div/div/div/div[2]/div/input</value>
      <webElementGuid>8833f86c-66a5-4219-9551-16f4680d737f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4a7b98b2-e784-41cc-9ada-c2b9931abb0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'id-m22ra6yanu303sehyor-input' and @form = 'id-m22ra6y6hg3w389tye-form']</value>
      <webElementGuid>bcec7237-f302-4573-ad98-5d61d283b6f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
