<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Download</name>
   <tag></tag>
   <elementGuidId>4e48e4c3-71ab-47ef-a889-afa0c6cfeccf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#link-to-download</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Generate File'])[1]/following::a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d6b1312d-3038-4160-9013-9d965160830b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>download</name>
      <type>Main</type>
      <value>info.txt</value>
      <webElementGuid>b6f1560d-988c-4dd2-a0d2-ddd0abdd93b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>link-to-download</value>
      <webElementGuid>3c068aed-08ce-41b2-9d99-91365776364d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>blob:https://demo.automationtesting.in/739a3948-3519-4fdc-8e32-63f6119acfd1</value>
      <webElementGuid>009b6e36-1def-4d3e-8263-1b7a0764bfbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Download</value>
      <webElementGuid>a0d21ef2-6d56-4ed4-8f1d-773bca62fffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;link-to-download&quot;)</value>
      <webElementGuid>f2f9bf52-4f54-4f67-b855-76f4aa4d2c01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generate File'])[1]/following::a[1]</value>
      <webElementGuid>86f50b05-4c2d-45a6-b7d6-4687c001c5bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter Data:'])[1]/following::a[1]</value>
      <webElementGuid>45d4fb36-ac9d-4887-8ffe-b8d53124e8c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generated PDF File to Download'])[1]/preceding::a[1]</value>
      <webElementGuid>930d7fc8-5176-48ec-8dd6-a8375b308513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter Data:'])[2]/preceding::a[1]</value>
      <webElementGuid>2c3cbcaf-1eda-4799-9fc5-ed16cd275f83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'link-to-download' and @href = 'blob:https://demo.automationtesting.in/739a3948-3519-4fdc-8e32-63f6119acfd1' and (text() = 'Download' or . = 'Download')]</value>
      <webElementGuid>b865f850-f09f-4fa2-aad2-d5e040aa3337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='link-to-download']</value>
      <webElementGuid>072ff92c-72e7-422c-9891-c3479308bec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Download')])[3]</value>
      <webElementGuid>118af23b-0f27-4a0a-8df0-15105e5bba71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'blob:https://demo.automationtesting.in/739a3948-3519-4fdc-8e32-63f6119acfd1')]</value>
      <webElementGuid>c370a82b-43db-4c96-a46e-4c18a3743c9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>a244bb38-712f-46ca-b391-73ac46fd4d53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
