<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Enter Data_textbox</name>
   <tag></tag>
   <elementGuidId>dee49a4c-16e6-463e-94d3-76136633a7b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#textbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id = 'textbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>4895d832-3141-4190-8259-3d6a376449c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>e46664e5-2ee1-4423-9723-0d9287a91263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>babb2f57-ecc7-4f65-960e-fc6d704bba64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>a5b227d7-497d-48a7-b3d8-f78ec4ba82a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textbox&quot;)</value>
      <webElementGuid>75df77e2-768b-4364-a720-e1687aca9989</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'textbox']</value>
      <webElementGuid>1ebd628d-4acc-4dbe-885d-7a6ad138a74d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='textbox']</value>
      <webElementGuid>09aa39f9-46f2-4f08-af5f-63e84fc3b91d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>f097d0f6-f40f-4120-ae11-9801ff1b9a82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
