<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Sort by latest</name>
   <tag></tag>
   <elementGuidId>b86c84d3-dceb-450b-bd5e-efc5fc2f0868</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-orderby-jv-result-xc5w-date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort by average rating'])[2]/following::li[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>722ebf3b-ebd5-460a-a9d4-04cf49bacebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>38c9b3fe-7d31-4539-8525-8e539abf4705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-orderby-jv-result-xc5w-date</value>
      <webElementGuid>d09bbcf1-ca81-4b64-9040-266f1443a313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>treeitem</value>
      <webElementGuid>48cf3a83-9f39-4b80-8c6b-8b12d93dc18b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d8450e68-2e36-4365-a8a8-a2ecabd60a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sort by latest</value>
      <webElementGuid>03a8d86e-632c-4c08-b417-a29ccc2b9293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-orderby-jv-result-xc5w-date&quot;)</value>
      <webElementGuid>b9d65591-35a4-4ecb-b8bf-6943e3feb511</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-orderby-jv-result-xc5w-date']</value>
      <webElementGuid>5d44d9d8-166b-4836-a289-6b41eafdab5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-orderby-jv-results']/li[4]</value>
      <webElementGuid>b116d67a-e402-4bee-bdb4-73c9c965873c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort by average rating'])[2]/following::li[1]</value>
      <webElementGuid>eb5b050a-bc2b-4cab-b65a-32a1286344ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort by popularity'])[2]/following::li[2]</value>
      <webElementGuid>a23d12ff-27ad-4c31-8b77-ef14000582ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort by price: low to high'])[2]/preceding::li[1]</value>
      <webElementGuid>2a4494d7-ff47-4bbb-9ee4-fd76d5ac5cc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort by price: high to low'])[2]/preceding::li[2]</value>
      <webElementGuid>e343a660-75a4-46b2-9b7d-a0cb6a34dbe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/ul/li[4]</value>
      <webElementGuid>b45526f0-ba5e-400f-9034-790112b9df3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-orderby-jv-result-xc5w-date' and (text() = 'Sort by latest' or . = 'Sort by latest')]</value>
      <webElementGuid>2495b375-ca8d-4e41-8f72-13690b102f3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
