<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add to cart</name>
   <tag></tag>
   <elementGuidId>806e1150-2f18-4b7e-b1da-1a020fe49050</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='No additional cover'])[1]/following::button[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>app-product-add-to-cart.ng-star-inserted > button.button.primary.pill-btn.pill-btn--blue.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>cx-page-slot >> internal:has-text=&quot;Slide 1 of 18 Slide 2 of 18 Slide 3 of 18 Slide 4 of 18 Slide 5 of 18 Slide 6 of&quot;i >> internal:label=&quot;Add to cart&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>895250bb-a123-40c6-b1f5-578de6aeb382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button primary pill-btn pill-btn--blue ng-star-inserted</value>
      <webElementGuid>376b7fd5-0a94-40e7-9e48-d8eab6b52146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Add to cart</value>
      <webElementGuid>dacbdb99-3e0b-4eae-8ecb-a45b089f8114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>SM-S928BZTFATS</value>
      <webElementGuid>48df4648-0d20-4f28-8535-22c5ea76a48f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-an-tr</name>
      <type>Main</type>
      <value>add-to-cart</value>
      <webElementGuid>3cce4ac8-b347-475f-9fdf-5199e5d4bd73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-an-la</name>
      <type>Main</type>
      <value>add to cart</value>
      <webElementGuid>810054ef-fa82-4fd2-b29d-aa27006e41ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelcode</name>
      <type>Main</type>
      <value>SM-S928BZTFATS</value>
      <webElementGuid>9cb0eaad-6989-4c85-8f50-fcd5dd477212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelname</name>
      <type>Main</type>
      <value>SM-S928B</value>
      <webElementGuid>852558c7-e21d-4234-af45-7a8cfd2e9b23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modeldisplay</name>
      <type>Main</type>
      <value>Galaxy S24 Ultra</value>
      <webElementGuid>940b0187-cb40-4abb-b7a3-1917df6bc014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelprice</name>
      <type>Main</type>
      <value>2399</value>
      <webElementGuid>a53d148c-5241-427d-9e7a-6176abe50fac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelrevenue</name>
      <type>Main</type>
      <value>2399</value>
      <webElementGuid>84b1f521-cfc4-435d-88bd-a723ca5c3aad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modelunit</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3fca4294-e13d-4641-bf61-e90dccfcd567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pvitype</name>
      <type>Main</type>
      <value>mobile</value>
      <webElementGuid>6af38c27-9962-4f38-a4b9-fe1be12d5e0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pvisubtype</name>
      <type>Main</type>
      <value>smartphone</value>
      <webElementGuid>54f23692-0e90-4f4a-9b98-3f623e5a6aa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pimsubtype</name>
      <type>Main</type>
      <value>galaxy s</value>
      <webElementGuid>98a47950-8368-4bbe-b7ed-f2da496add0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Add to cart </value>
      <webElementGuid>47919046-7469-4351-ba13-077d0497564c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[@class=&quot;au&quot;]/cx-storefront[@class=&quot;v2 ProductDetailsPageTemplate stop-navigating&quot;]/main[@class=&quot;mouse-focus&quot;]/cx-page-layout[@class=&quot;ProductDetailsPageTemplate ng-star-inserted&quot;]/cx-page-slot[@class=&quot;ProductSummarySlotContent has-components ng-star-inserted&quot;]/app-product-add-to-cart[@class=&quot;ng-star-inserted&quot;]/button[@class=&quot;button primary pill-btn pill-btn--blue ng-star-inserted&quot;]</value>
      <webElementGuid>cc6cf480-71f5-483b-b02f-1b4a22b35d6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No additional cover'])[1]/following::button[1]</value>
      <webElementGuid>b57ecb34-378f-4fb1-ae05-969abee8ad0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Protect your device from accidental liquid &amp; screen damage up to 2 years.'])[1]/following::button[2]</value>
      <webElementGuid>bc2457c1-a739-4734-9894-46d99dacf7f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$179.93/mo or $2,399.00'])[3]/preceding::button[1]</value>
      <webElementGuid>3f7c9b94-9bb6-4c11-9c54-f36742b85a6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//cx-page-slot[3]/app-product-add-to-cart/button</value>
      <webElementGuid>78214493-826f-4eba-837a-7cdf8a8f3f26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Add to cart ' or . = ' Add to cart ')]</value>
      <webElementGuid>6452b3e3-71cb-4d12-85b4-8a34ffc4ab0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
