<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>3490e1ac-255d-4c0f-9ebb-da34744e383d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.remove.tdfocus-1680098631164</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-8']/div/div/form/table/tbody/tr/td/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c911e72f-dc87-4f72-952d-8110394c9998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://cms.demo.katalon.com/cart/?remove_item=72b32a1f754ba1c09b3695e0cb6cde7f&amp;_wpnonce=bffbab091b</value>
      <webElementGuid>a2814995-9de4-40e6-af0f-ccaa42ff1290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>remove tdfocus-1680098631164</value>
      <webElementGuid>9ee4c72e-271d-4301-92dc-c67a700702d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Remove this item</value>
      <webElementGuid>95d70151-7e4f-4a46-813b-43199c40dad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-product_id</name>
      <type>Main</type>
      <value>57</value>
      <webElementGuid>a7652bca-10eb-49e2-b350-a2699c44c814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-product_sku</name>
      <type>Main</type>
      <value>POSTER-SHIP-YOUR-IDEA</value>
      <webElementGuid>83c617b7-72c3-417f-89cb-a925f9e1fa8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>1d54433d-41fa-40dd-8e34-c4b6049caed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-8&quot;)/div[@class=&quot;entry-content&quot;]/div[@class=&quot;woocommerce&quot;]/form[@class=&quot;woocommerce-cart-form&quot;]/table[@class=&quot;shop_table shop_table_responsive cart woocommerce-cart-form__contents&quot;]/tbody[1]/tr[@class=&quot;woocommerce-cart-form__cart-item cart_item&quot;]/td[@class=&quot;product-remove&quot;]/a[@class=&quot;remove tdfocus-1680098631164&quot;]</value>
      <webElementGuid>007f687b-4c80-4291-8eb7-ace0077336b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-8']/div/div/form/table/tbody/tr/td/a</value>
      <webElementGuid>30ddf46f-689d-46f5-a460-4f013c963b43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'×')]</value>
      <webElementGuid>408d5267-c004-46d9-884a-61c4cf50f414</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/following::a[1]</value>
      <webElementGuid>d6069728-0efb-43a0-9e4e-cb24d3fb1eb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity'])[1]/following::a[1]</value>
      <webElementGuid>8de44ed9-0384-4bfb-a5e8-2256df61070a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ship Your Idea'])[1]/preceding::a[2]</value>
      <webElementGuid>5ee8d159-0c58-4065-a484-706184e2bf01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$'])[1]/preceding::a[3]</value>
      <webElementGuid>0630500f-c41b-49f7-8fa1-1ab195118d85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='×']/parent::*</value>
      <webElementGuid>d11faba8-457e-42aa-9b3e-a609be718eae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://cms.demo.katalon.com/cart/?remove_item=72b32a1f754ba1c09b3695e0cb6cde7f&amp;_wpnonce=bffbab091b')]</value>
      <webElementGuid>5b0b478f-d430-4f58-a567-5083c55f2a59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>a7e38282-9f64-45aa-912d-e9b9b9bd640b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://cms.demo.katalon.com/cart/?remove_item=72b32a1f754ba1c09b3695e0cb6cde7f&amp;_wpnonce=bffbab091b' and (text() = '×' or . = '×')]</value>
      <webElementGuid>8460efae-1c46-4089-99bf-a555086ab60f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
