<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Venezuela_calc_shipping_state</name>
   <tag></tag>
   <elementGuidId>6230d8bd-4608-4133-a125-9e71372c37f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#calc_shipping_state</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='calc_shipping_state']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ca8ef950-91f1-492e-8970-ac95201de7b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bba3b5a3-09f1-4825-8b15-80faabb21aa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>calc_shipping_state</value>
      <webElementGuid>c35b2c03-fee6-4a2e-8f9d-ce7d6473b735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>calc_shipping_state</value>
      <webElementGuid>f7564456-5b05-4968-ac1c-e8581552f190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>State / County</value>
      <webElementGuid>a070d797-da66-45a0-882b-bf9be7c6ec6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text undefined tdfocus-1680079146930</value>
      <webElementGuid>0ee9bc8e-2050-454a-a0fc-2b7888110654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>State / County</value>
      <webElementGuid>9240a0fc-1e48-499b-be35-bb1410800071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calc_shipping_state&quot;)</value>
      <webElementGuid>b98f7368-ded1-4d15-85e3-5a4be84a1811</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='calc_shipping_state']</value>
      <webElementGuid>981f2fb1-a4c8-4072-8bcb-0774486215a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='calc_shipping_state_field']/input</value>
      <webElementGuid>476fc4ad-4f06-4b6b-955a-9f237967b273</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/input</value>
      <webElementGuid>2a9519bb-3b96-4b33-a53d-e1effbdff97d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'calc_shipping_state' and @name = 'calc_shipping_state' and @placeholder = 'State / County']</value>
      <webElementGuid>9f65e7e3-926b-4eec-aa35-5f26df23794f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
