<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Venezuela_calc_shipping_postcode</name>
   <tag></tag>
   <elementGuidId>a3fa803d-1663-4ee1-98c3-c4e80f9bfa2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#calc_shipping_postcode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='calc_shipping_postcode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c655a109-b2f8-48ef-a8b0-40c4025ac83d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2d29f891-ab2f-4cbe-b182-4dcb8cb397c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text</value>
      <webElementGuid>0407c6bf-d35f-43b2-a7d2-fad58760edea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>70000</value>
      <webElementGuid>4987486a-3b4c-4916-b177-ce697d5e6f9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Postcode / ZIP</value>
      <webElementGuid>d7a526ad-42f9-414c-8e56-e501af9eafd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>calc_shipping_postcode</value>
      <webElementGuid>35282c02-c831-4501-946c-8470efcef5a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>calc_shipping_postcode</value>
      <webElementGuid>d06847ba-dc8e-4c6b-86fa-17dd2395dc85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Postcode / ZIP</value>
      <webElementGuid>35691caf-6a51-496b-ba67-6a016610d86d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calc_shipping_postcode&quot;)</value>
      <webElementGuid>a4290a04-f0c2-4413-8939-b40eb4414f35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='calc_shipping_postcode']</value>
      <webElementGuid>7a01c306-1e95-45b8-a6ae-a022a771abb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='calc_shipping_postcode_field']/input</value>
      <webElementGuid>c11ba08b-79fb-4249-ac5c-cf4f5fb81a31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[4]/input</value>
      <webElementGuid>5ec46f79-7b96-4a41-888e-170a49c3b895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Postcode / ZIP' and @name = 'calc_shipping_postcode' and @id = 'calc_shipping_postcode']</value>
      <webElementGuid>c3c51f5a-355b-4e3d-93fd-2b5b57154422</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
