<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(id(, , myFile, , ))_filename</name>
   <tag></tag>
   <elementGuidId>9978e56e-48d5-411e-8bd5-4be0140ee36a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#myFile</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'file' and @id = 'myFile' and @name = 'filename']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d42f020e-2779-4df7-9034-990300a184fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>33c2e377-8200-48b5-8ec2-f5ca31d90010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>myFile</value>
      <webElementGuid>53fb001d-a636-4bf8-babc-332386fe81fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>filename</value>
      <webElementGuid>78a5c108-0c9a-4d74-b7b9-04dfa758bdbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myFile&quot;)</value>
      <webElementGuid>efa22eb9-3c48-429d-b086-687296b51bea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/iframe__iframeResult</value>
      <webElementGuid>e5cdbbbd-d367-413e-8299-c183b099d851</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'myFile' and @name = 'filename']</value>
      <webElementGuid>f7fb5be2-99a4-40f4-962e-31de7e05aaad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='myFile']</value>
      <webElementGuid>f1aa69e7-50af-4ca4-995e-7ec01c19f423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>09e8be4e-f359-4f32-a134-b40f8cbae250</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
