<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Venezuela_calc_shipping_city</name>
   <tag></tag>
   <elementGuidId>b1ecd954-f8bb-4f06-aa90-f1d9db1a7d23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#calc_shipping_city</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='calc_shipping_city']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a2e525ed-51fc-48f2-88ef-fb3bf6a154d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ea573931-9975-4270-9e7b-14ac79230701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text</value>
      <webElementGuid>dbb7490c-d7ce-46c9-86eb-88f9a94447f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>HCM</value>
      <webElementGuid>e343e927-99b9-488c-b63c-3c1ee656fde1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Town / City</value>
      <webElementGuid>d74da647-294b-4975-844b-b7c829e2c6b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>calc_shipping_city</value>
      <webElementGuid>e00fb1a5-915b-4e07-81ff-ddf9d991f497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>calc_shipping_city</value>
      <webElementGuid>d16d25ea-7234-4195-be02-f43728342fde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Town / City</value>
      <webElementGuid>c9c86ba1-d913-4d31-97ae-784dadcae300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calc_shipping_city&quot;)</value>
      <webElementGuid>3079825f-eaa4-4bab-92e5-3dfa7b171c48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='calc_shipping_city']</value>
      <webElementGuid>fb6a2a6f-b752-40b5-8286-802d8a07174d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='calc_shipping_city_field']/input</value>
      <webElementGuid>d628d4be-47ee-4bf8-ba68-fa4ae3032bcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]/input</value>
      <webElementGuid>ee38b774-5f96-4479-b988-e392c4ffd732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Town / City' and @name = 'calc_shipping_city' and @id = 'calc_shipping_city']</value>
      <webElementGuid>8f2f9620-7638-4eba-8a54-b7c7771080a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
