<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(optional)_billing_postcode</name>
   <tag></tag>
   <elementGuidId>cdc233a6-350d-4bdb-a5e1-595a4ab01e11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billing_postcode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billing_postcode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>85b13d56-cbf3-4ca6-a980-827bd8158f84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>54671e48-09a1-4ac9-b63b-a0a67fe580f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text </value>
      <webElementGuid>c79bbfa3-1b4e-4fc5-b675-3afa4e030f84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billing_postcode</value>
      <webElementGuid>2a91c904-85d6-431d-a2f5-5b64687d1487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing_postcode</value>
      <webElementGuid>e7a3fd0b-ee47-4628-bbdb-88dc6df3a4c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>70000</value>
      <webElementGuid>51c1a197-bdb7-497b-93aa-b61a071ed0ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>postal-code</value>
      <webElementGuid>a66a8398-f460-496d-b869-dd64ab232384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing_postcode&quot;)</value>
      <webElementGuid>feba3d32-f964-4581-8de0-e5040d886070</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billing_postcode']</value>
      <webElementGuid>0ee0f9b8-972a-4c3f-955a-84d567c6e716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='billing_postcode_field']/span/input</value>
      <webElementGuid>1c78011d-5ac9-4412-9b3f-f868d28cd6a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[7]/span/input</value>
      <webElementGuid>3613cc67-7535-4ee5-9794-ee8df2fd454a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'billing_postcode' and @id = 'billing_postcode']</value>
      <webElementGuid>4d5ed3e1-8024-4e5f-bf6d-7316f4502388</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
