<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Venezuela</name>
   <tag></tag>
   <elementGuidId>f6dd0783-863e-41b5-8dd1-4d172d8d41e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-billing_country-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-billing_country-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>716e3b31-2de5-4e3d-9b67-3d008a0ef4bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered tdfocus-1680082830011</value>
      <webElementGuid>0a7187a4-c82d-4028-bc0f-dada53842d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-billing_country-container</value>
      <webElementGuid>b1a96afd-73f1-49b3-8e15-c278108790bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>d5cad5b7-2624-49db-8f68-654386a36b50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>505c44ed-241f-409b-aa36-2ad6c57378f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Venezuela</value>
      <webElementGuid>4cf18653-0823-4800-b296-eb1daccb3109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Venezuela</value>
      <webElementGuid>871c6960-bf30-46a4-b456-2a121a5dc8e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-billing_country-container&quot;)</value>
      <webElementGuid>b85a5c8c-70b4-4991-90ca-fd24f6264520</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-billing_country-container']</value>
      <webElementGuid>c4ee15aa-d11d-4120-8dd4-40ad5f0ef302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='billing_country_field']/span/span/span/span/span</value>
      <webElementGuid>f1b3c2df-74df-4baa-acb3-0bc48be3bab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::span[5]</value>
      <webElementGuid>7b967237-9da5-4b45-ad38-334a9abc0423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/preceding::span[3]</value>
      <webElementGuid>2fe8545f-b49a-4257-99b3-094892ab07db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span/span</value>
      <webElementGuid>fe6df20c-ee73-44d0-ab23-e0f297d58b56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-billing_country-container' and @title = 'Venezuela' and (text() = 'Venezuela' or . = 'Venezuela')]</value>
      <webElementGuid>2aecd6c6-de31-40de-8028-101d6000f069</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
