<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_(optional)_order_comments</name>
   <tag></tag>
   <elementGuidId>7673f370-e81c-42b1-9bf9-99b7182b9dfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#order_comments</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='order_comments']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>80725278-15b6-4ff8-a5df-f39de073888b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>order_comments</value>
      <webElementGuid>d1ac69c5-341a-4af9-b45b-e45087c497e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text tdfocus-1680082889069</value>
      <webElementGuid>6c796dd7-b211-48ae-a7c0-762796410ded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>order_comments</value>
      <webElementGuid>49f9b181-d1c7-47e4-aa85-962920251115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Notes about your order, e.g. special notes for delivery.</value>
      <webElementGuid>8a21b876-6279-4434-9b20-333c9aebc075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>de1b5cf3-27a4-4801-9008-03cc219b9b4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>aa467a8b-532f-4d10-a054-865705319053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gramm</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1b77a01d-626d-4915-b1c1-c1046a5f6437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wt-ignore-input</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>16272e19-6871-481e-a2ab-b1f73a51fb58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-quillbot-element</name>
      <type>Main</type>
      <value>d8F8FvYGPsNodR3wvoqN1</value>
      <webElementGuid>57c0fab8-35bf-4bd2-bec1-9de79ea6fbd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order_comments&quot;)</value>
      <webElementGuid>a470ab24-4c1e-49a0-be51-a582b3ea7b7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='order_comments']</value>
      <webElementGuid>51f8c57e-4969-48d1-a000-1263deed6786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='order_comments_field']/span/textarea</value>
      <webElementGuid>582ba524-cea3-475d-b672-8cdf06fc89af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>3d99e8f5-ffbe-4cb7-a204-08b55775879f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'order_comments' and @id = 'order_comments' and @placeholder = 'Notes about your order, e.g. special notes for delivery.']</value>
      <webElementGuid>a95592cc-9aaa-4cb9-8ad2-15dd2a4fbf75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
