<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Home</name>
   <tag></tag>
   <elementGuidId>5e8b3b5e-1808-4968-a105-1912f77618ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.-link--channel-name.pl6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='company blog'])[1]/following::span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Home&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e618fc82-6638-44e1-8f32-26090c30997a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-link--channel-name pl6</value>
      <webElementGuid>01771af4-6729-4d8c-9e5b-abf491602377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Home</value>
      <webElementGuid>d1dde8a1-d796-4f56-97b3-1ef8cdf88939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;left-sidebar&quot;)/div[@class=&quot;left-sidebar--sticky-container js-sticky-leftnav&quot;]/nav[1]/ol[@class=&quot;nav-links&quot;]/li[1]/ol[@class=&quot;nav-links&quot;]/li[@class=&quot;ps-relative  youarehere&quot;]/a[@class=&quot;s-block-link pl8 js-gps-track nav-links--link -link__with-icon&quot;]/div[@class=&quot;d-flex ai-center&quot;]/span[@class=&quot;-link--channel-name pl6&quot;]</value>
      <webElementGuid>f0d88df8-a90e-48a0-a1bf-c014c3b03882</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='company blog'])[1]/following::span[1]</value>
      <webElementGuid>f5e81c69-129f-45a8-9292-77fc97745ca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='more stack exchange communities'])[1]/following::span[1]</value>
      <webElementGuid>0f850ead-cfd6-45cb-ae12-a020c49cde17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Questions'])[1]/preceding::span[1]</value>
      <webElementGuid>f514d96d-387a-4de6-84fe-4a005460abc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tags'])[1]/preceding::span[2]</value>
      <webElementGuid>73bc7b3b-eb67-4b42-a9f7-324bf84ca563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Home']/parent::*</value>
      <webElementGuid>13add1fd-f2b1-4676-8908-a2531d36aed9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Home' or . = 'Home')]</value>
      <webElementGuid>a7c34e56-3d4c-47c7-8285-ac8bd695af1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='left-sidebar']/div/nav/ol/li/ol/li/a/div/span</value>
      <webElementGuid>cf0d97a8-759c-48ae-b21c-62df34a9baa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/span</value>
      <webElementGuid>f7c6c9cd-0d5a-4f1b-9226-07860cc7467e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
