<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Next</name>
   <tag></tag>
   <elementGuidId>fa242ec0-7459-464d-b8e3-29cb6600ec91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.quantity-button.quantity-up.tdfocus-1679826307207</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7d96fd95-7daa-4cd7-8ef1-92eae20aaa93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>quantity-button quantity-up tdfocus-1679826307207</value>
      <webElementGuid>4073ae81-8278-4bbb-b921-7e73eb68de72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-57&quot;)/div[@class=&quot;summary entry-summary&quot;]/form[@class=&quot;cart&quot;]/div[@class=&quot;quantity&quot;]/div[@class=&quot;quantity-nav&quot;]/div[@class=&quot;quantity-button quantity-up tdfocus-1679826307207&quot;]</value>
      <webElementGuid>1ed3e0eb-460f-4f3f-a1ea-ac4d15997a55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-57']/div[2]/form/div/div/div</value>
      <webElementGuid>e31779e9-68cb-4bfc-b637-37d9e392443a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div</value>
      <webElementGuid>e122148b-475e-442f-b68f-fa0ec1d10106</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
